main: fire.spigot_maze_generator.SpigotMazeGenerator
name: MazeGenerator
version: 1.0
author: FireFlower
description: Used to make mazes :D
load: startup
commands:
  mazeGen:
    description: Creates a maze
    usage: /mazeGen xLenght zLength